In [107]:
import random
import numpy as np
from time import sleep
i=1
l=[]
done=[]
s=''
for i in range(1,91):
    if i%10!=0:
        l.append(str(i)+',')
    else:
        if(i!=90):
            l.append(str(i)+';')
        else:
            l.append(str(i))
    i+=1
for k in l:
    s +=k
ss= "'"+ s + "'"
y = np.matrix(s)
print(y,"\n\n")
sleep(5)

def numb():
    
    def printout(j):
        q=j-1
        m=int(q/10)
        n=q%10
        y[m,n]=0
        print("\n\n",y)
        
        
    def val():
        j = random.randint(1,90)
        
        if j not in done:
            done.append(j)
            print("New Number: ",j)
            printout(j)
            print("\nRecent:",done)
        else:
            val()
     
    
        
    
    def choice():
        if len(done)!=90:
            ask = input("\nPress Y to continue and N to quit\n")
            if ask=='Y' or ask=='y':
                print("\n\n")
                numb()
            elif ask=='N' or ask=='n':
                print("Thanks for playing")
            else:
                choice()
        else:
            print("Game over")
        
    
    

        
        
    val()
    choice()
    
numb()


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]] 


New Number:  34


 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33  0 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]]

Recent: [34]

Press Y to continue and N to quit
y



New Number:  9


 [[ 1  2  3  4  5  6  7  8  0 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33  0 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]]

Recent: [34